region: eu-west-1
hostport: 3000
containerport: 3000
role: frontend-application
environment: prod
iac: terraform-workspace-aws-prod-application-eu-west-1-apps-agglayer-docs
team_name: documentation
memory: 1024
cpu: 512
