name: Deploy docker image to GCP
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        required: false
        type: choice
        description: "Select the environment to deploy to (optional for pushes)"
        options:
          - prod

permissions:
  contents: read
  id-token: write

jobs:
  docker-release:
    uses: 0xPolygon/pipelines/.github/workflows/gcp_pipeline_release_image.yaml@main
    with:
      image_name: agglayer-docs
      environment: ${{ inputs.environment || 'dev' }}
